# Generated by Django 4.2.3 on 2023-07-22 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_rename_imgor_game_main_imgor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 17, 48, 31, 619760), verbose_name='дата истечения'),
        ),
    ]
