# Generated by Django 4.2.3 on 2023-07-23 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 18, 58, 42, 505423), verbose_name='дата истечения'),
        ),
        migrations.CreateModel(
            name='AdditionalGamesPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgor', models.ImageField(default='games/unknown.png', upload_to='games/', verbose_name='изображение')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='games.game', verbose_name='игра')),
            ],
            options={
                'verbose_name': 'дополнительное фото',
                'verbose_name_plural': 'дополнительные фото',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='additional_images',
            field=models.ManyToManyField(related_name='games', to='games.additionalgamesphotos', verbose_name='дополнительные изображения'),
        ),
    ]
