# Generated by Django 4.2.3 on 2023-07-23 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_invitecard_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 19, 2, 27, 905977), verbose_name='дата истечения'),
        ),
    ]
