# Generated by Django 4.2.3 on 2023-07-23 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='main_imgor',
            new_name='main_img',
        ),
        migrations.RemoveField(
            model_name='additionalgamesphotos',
            name='imgor',
        ),
        migrations.AddField(
            model_name='additionalgamesphotos',
            name='img',
            field=models.ImageField(default='games/unknown.png', upload_to='games/', verbose_name='дополнительное изображение'),
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 0, 56, 27, 1924), verbose_name='дата истечения'),
        ),
    ]
