# Generated by Django 4.2.3 on 2023-07-24 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_rename_main_imgor_game_main_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 13, 40, 25, 20308), verbose_name='дата истечения'),
        ),
    ]
