# Generated by Django 4.2.3 on 2023-07-24 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_game_main_img_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 15, 32, 26, 435219), verbose_name='дата истечения'),
        ),
    ]
